name: XAI_LLM_G4
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - pip:
    - numpy==1.26.4
    - pandas==2.2.2
    - torch==2.2.1
    - einops==0.8.0
    - jaxtyping==0.2.28
    - plotly==5.19.0
    - transformer_lens==1.17.0
